### ISSUE TITLE
短链接不支持cdn.jsdelivr.net

### ISSUE THREAD

**Issue by Boring1998** [x-dr/short#10]
短链接不支持cdn.jsdelivr.net
短链生成后，指向了原文件地址，

https://d.131213.xyz/F79Q

https://[raw.githubusercontent.com](https://raw.githubusercontent.com/Boring1998/yunpan/main/PC%E8%87%AA%E7%94%A8%E5%BF%85%E8%A3%85/UAC%E7%99%BD%E5%90%8D%E5%8D%95%E5%B0%8F%E5%B7%A5%E5%85%B7%20v1.8.2.zip)/Boring1998/yunpan/main/PC%E8%87%AA%E7%94%A8%E5%BF%85%E8%A3%85/UAC%E7%99%BD%E5%90%8D%E5%8D%95%E5%B0%8F%E5%B7%A5%E5%85%B7%20v1.8.2.zip

**Comment by x-dr** [comment]
程序是302跳转的，不支持是你的问题
